[tool.black]
line-length = 120

[tool.mypy]
python_version = "3.11"
warn_return_any = false
warn_unused_configs = true
files = "filedrop/**/*.py"
check_untyped_defs = true

[tool.pylint]
disable = [
    "line-too-long",
    "missing-module-docstring",
    "fixme",
    "too-few-public-methods",
    "too-many-branches",
    "too-many-arguments",
    "too-many-instance-attributes"
]
ignore = [
    "filedrop/tests"
]

[tool.pylint.basic]
# allow single letter variable names
good-names-rgxs = [
    "[a-z]{1}"
]